config/routes.rb
Rails.application.routes.draw do
  resources :news
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  get 'oauths/oauth'
  get 'oauths/callback'
  use_doorkeeper_openid_connect
  get 'pages/index'
  use_doorkeeper
  root 'pages#index'
  get '/minha_conta' => 'users#show', :as => 'user'
  resources :users, only: [:new, :create, :edit]
  patch '/users/:id' => 'users#update', :as => 'atualizar_usuario'
  get '/users/dados' => 'users#adicionar_dados', :as => 'adicionar_dados'
  get '/painel' => 'users#painel', :as => 'painel'
  get '/sign_up' => 'users#new', :as => 'sign_up'
  delete '/users/:id' => 'users#destroy', :as => 'apagar_usuario'
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :sessions, only: [:new, :create]
  get '/log_in', to: 'sessions#new', as: :log_in
  post '/log_inn', to: 'sessions#create', as: :log_inn
  delete '/log_out', to: 'sessions#destroy', as: :log_out
  get '/log_out', to: 'sessions#destroy', as: :log_out_extern
  #Login com oauth
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with Github, Facebook
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider
  #Análises
  get '/analise' => 'reviews#index'
  post '/analise' => 'reviews#criar'
  patch '/analise' => 'reviews#atualizar'
  post '/analiseDeletar' => 'reviews#deletar'

  #Registro em curso
  get 'cursos/registro/' => 'course_registrations#new', :as => 'registro_curso'
  get 'cursos/registro/quiz' => 'course_registrations#consulta_quiz', :as => 'consulta_quiz'
  get 'cursos/destaque' => 'course_registrations#cursos_destaque'
  post 'cursos/registro/' => 'course_registrations#create', :as => 'registrado_curso'
  # post 'cursos/preencher_quiz/' => 'course_registrations#preencher_quiz', :as => 'preencher_quiz'
  post '/cursos/confirmar' => 'course_registrations#confirmacao_matricula', :as => 'confirmacao'
  post '/matricula/alunos/' => 'course_registrations#matricula_alunos', :as => 'matricula_alunos'

  #Avaliação curso
  post '/curso/avaliar' => 'course_ratings#avaliar_curso', :as => 'avaliar_curso'
  get '/curso/avaliacoes' => 'course_ratings#index', :as => 'index'

  #Api Keys
  resources :api_accesses, only: [:new,:create,:index,:destroy]

  scope '/api' do
    scope '/v1' do
      #Cursos
      post '/cursos/registrar' => 'courses#registrar_curso', :as => 'registrar_curso'
      get '/cursos/aprovar' => 'courses#index_cursos_pendentes', :as => 'index_cursos_pendentes'
      post '/cursos/aprovar' => 'courses#aprovar_curso', :as => 'aprovar_curso'
      get '/cursos/' => 'courses#index', :as => 'cursos'
      post '/cursos/buscar' => 'courses#buscar_cursos', :as => 'buscar_cursos'
      #Categoria de curso
      post '/categorias_cursos/adicionar' => 'course_categories#adicionar_categoria', :as => 'adicionar_categoria'
      post '/categorias_cursos/atualizar' => 'course_categories#atualizar_categoria', :as => 'atualizar_categoria'
      get '/categorias_cursos/' => 'course_categories#index', :as => 'categorias_cursos'
      #Escolas
      post '/escolas/registrar' => 'schools#registrar_escola', :as => 'registrar_escola'
      get '/escolas/' => 'schools#index', :as => 'escolas'
      #Registros de Cursos
      get '/registros/' => 'course_registrations#cursos_usuario', :as => 'cursos_usuario'
      #Certificados
      post 'certificados/adicionar' => 'certificates#adicionar_certificado', :as => 'adicionar_certificado'
      get 'certificados/detalhar' => 'certificates#detalhes_certificado', :as => 'detalhes_certificado'
      get 'certificados/' => 'certificates#certificado_usuario', :as => 'certificado_usuario'
      #Fale conosco
      post '/fale_conosco/conversa' => 'contact_us_conversations#index', :as => 'conversa'
      post '/fale_conosco/conversa_usuario' => 'contact_us_conversations#conversa_usuario', :as => 'conversa_usuario'
      post '/fale_conosco/mensagens' => 'contact_us_conversations#detalhar_conversa', :as => 'detalhar_conversa'
      post '/fale_conosco/adicionar' => 'contact_us_conversations#adicionar_conversa', :as => 'adicionar_conversa'
      post '/fale_conosco/apagar_mensagem' => 'contact_us_messages#apagar_mensagem', :as => 'apagar_mensagem'
      post '/fale_conosco/apagar_conversa' => 'contact_us_conversations#apagar_conversa', :as => 'apagar_conversa'
      patch '/fale_conosco/atualizar_mensagem' => 'contact_us_messages#atualizar_mensagem', :as => 'atualizar_mensagem'
    end
  end
end

app/models/news.rb
class News < ApplicationRecord
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  def index
    news = News.all
    hash_news = news.map do |c|
      {'id' => c.id,
       'tag' => c.tag,
       'titulo' => c.title,                 
       'link' => c.link,
       'icone' => c.icon
      }
    end
    if !hash_news.empty?
      render status: 200, json: {
          noticias: hash_news,
      }.to_json
    else
      render status: 400, json: {
        mensagem: "Não existe notícias.",
      }.to_json
    end
  end

  # GET /news/1
  def show
    respond_to do |format|
      if @news
        format.json { render :show, status: :ok, location: @news }
      else
        format.json { render json: {"mensagem": "Essa notícia não existe!"}, status: :unprocessable_entity }
      end
    end
  end

  # POST /news
  def create
    @news = News.new(news_params)
    if @news.save
      render status: 200, json: {
        mensagem: "A notícia foi criada com sucesso!",
      }.to_json
    else
      render status: 400, json: {
        mensagem: "Não foi possível criar a notícia.",
      }.to_json
    end
  end

  # PATCH/PUT /news/1
  def update
    respond_to do |format|
      if @news
        if @news.update(news_params)
          format.json { render :show, status: :ok, location: @news }
        else
          format.json { render json: @news.errors, status: :unprocessable_entity }
        end
      else
        format.json { render json: {"mensagem": "Essa notícia não existe!"}, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  def destroy
    respond_to do |format|
      if @news
        if @news.destroy
          format.json { render json: {"mensagem": "Notícia foi excluída com sucesso!"}, status: :ok }
        else
          format.json { render json: @news.errors, status: :unprocessable_entity }
        end
      else
        format.json { render json: {"mensagem": "Essa notícia não existe!"}, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_news
      begin
        @news = News.find(params[:id])
      rescue
        @new = nil
      end
    end

    def news_params
      params.require(:news).permit(:tag, :title, :link, :icon)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_with(model: news, local: true) do |form| %>
  <% if news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tag %>
    <%= form.text_field :tag %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="field">
    <%= form.label :icon %>
    <%= form.text_field :icon %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<p id="notice"><%= notice %></p>

<h1>News</h1>

<table>
  <thead>
    <tr>
      <th>Tag</th>
      <th>Title</th>
      <th>Link</th>
      <th>Icon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.tag %></td>
        <td><%= news.title %></td>
        <td><%= news.link %></td>
        <td><%= news.icon %></td>
        <td><%= link_to 'Show', news %></td>
        <td><%= link_to 'Edit', edit_news_path(news) %></td>
        <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News', new_news_path %>

app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tag:</strong>
  <%= @news.tag %>
</p>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Link:</strong>
  <%= @news.link %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @news.icon %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>