config/routes.rb
Rails.application.routes.draw do
  resources :news
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  get 'oauths/oauth'
  get 'oauths/callback'
  use_doorkeeper_openid_connect
  get 'pages/index'
  use_doorkeeper
  root 'pages#index'
  get '/minha_conta' => 'users#show', :as => 'user'
  resources :users, only: [:new, :create, :edit]
  patch '/users/:id' => 'users#update', :as => 'atualizar_usuario'
  get '/users/dados' => 'users#adicionar_dados', :as => 'adicionar_dados'
  get '/painel' => 'users#painel', :as => 'painel'
  get '/sign_up' => 'users#new', :as => 'sign_up'
  delete '/users/:id' => 'users#destroy', :as => 'apagar_usuario'
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :sessions, only: [:new, :create]
  get '/log_in', to: 'sessions#new', as: :log_in
  post '/log_inn', to: 'sessions#create', as: :log_inn
  delete '/log_out', to: 'sessions#destroy', as: :log_out
  get '/log_out', to: 'sessions#destroy', as: :log_out_extern
  #Login com oauth
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with Github, Facebook
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider
  #Análises
  get '/analise' => 'reviews#index'
  post '/analise' => 'reviews#criar'
  patch '/analise' => 'reviews#atualizar'
  post '/analiseDeletar' => 'reviews#deletar'

  #Registro em curso
  get 'cursos/registro/' => 'course_registrations#new', :as => 'registro_curso'
  get 'cursos/registro/quiz' => 'course_registrations#consulta_quiz', :as => 'consulta_quiz'
  get 'cursos/destaque' => 'course_registrations#cursos_destaque'
  post 'cursos/registro/' => 'course_registrations#create', :as => 'registrado_curso'
  # post 'cursos/preencher_quiz/' => 'course_registrations#preencher_quiz', :as => 'preencher_quiz'
  post '/cursos/confirmar' => 'course_registrations#confirmacao_matricula', :as => 'confirmacao'
  post '/matricula/alunos/' => 'course_registrations#matricula_alunos', :as => 'matricula_alunos'

  #Avaliação curso
  post '/curso/avaliar' => 'course_ratings#avaliar_curso', :as => 'avaliar_curso'
  get '/curso/avaliacoes' => 'course_ratings#index', :as => 'index'

  #Api Keys
  resources :api_accesses, only: [:new,:create,:index,:destroy]

  scope '/api' do
    scope '/v1' do
      #Cursos
      post '/cursos/registrar' => 'courses#registrar_curso', :as => 'registrar_curso'
      get '/cursos/aprovar' => 'courses#index_cursos_pendentes', :as => 'index_cursos_pendentes'
      post '/cursos/aprovar' => 'courses#aprovar_curso', :as => 'aprovar_curso'
      get '/cursos/' => 'courses#index', :as => 'cursos'
      post '/cursos/buscar' => 'courses#buscar_cursos', :as => 'buscar_cursos'
      #Categoria de curso
      post '/categorias_cursos/adicionar' => 'course_categories#adicionar_categoria', :as => 'adicionar_categoria'
      post '/categorias_cursos/atualizar' => 'course_categories#atualizar_categoria', :as => 'atualizar_categoria'
      get '/categorias_cursos/' => 'course_categories#index', :as => 'categorias_cursos'
      #Escolas
      post '/escolas/registrar' => 'schools#registrar_escola', :as => 'registrar_escola'
      get '/escolas/' => 'schools#index', :as => 'escolas'
      #Registros de Cursos
      get '/registros/' => 'course_registrations#cursos_usuario', :as => 'cursos_usuario'
      #Certificados
      post 'certificados/adicionar' => 'certificates#adicionar_certificado', :as => 'adicionar_certificado'
      get 'certificados/detalhar' => 'certificates#detalhes_certificado', :as => 'detalhes_certificado'
      get 'certificados/' => 'certificates#certificado_usuario', :as => 'certificado_usuario'
      #Fale conosco
      post '/fale_conosco/conversa' => 'contact_us_conversations#index', :as => 'conversa'
      post '/fale_conosco/conversa_usuario' => 'contact_us_conversations#conversa_usuario', :as => 'conversa_usuario'
      post '/fale_conosco/mensagens' => 'contact_us_conversations#detalhar_conversa', :as => 'detalhar_conversa'
      post '/fale_conosco/adicionar' => 'contact_us_conversations#adicionar_conversa', :as => 'adicionar_conversa'
      post '/fale_conosco/apagar_mensagem' => 'contact_us_messages#apagar_mensagem', :as => 'apagar_mensagem'
      post '/fale_conosco/apagar_conversa' => 'contact_us_conversations#apagar_conversa', :as => 'apagar_conversa'
      patch '/fale_conosco/atualizar_mensagem' => 'contact_us_messages#atualizar_mensagem', :as => 'atualizar_mensagem'
    end
  end
end

app/models/api_access.rb
class ApiAccess < ApplicationRecord
  validates :cpf, length: { is: 14 }
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/certificate.rb
class Certificate < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :school
  belongs_to :course_category, optional: true
  has_one_attached :logo
  has_many :certificates
  has_many :course_registrations
  has_many :course_rating
end

app/models/course_rating.rb
class CourseRating < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/curso.rb
class Curso < ApplicationRecord
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many :quiz_questions
end

app/models/quiz_answer.rb
class QuizAnswer < ApplicationRecord
  belongs_to :quiz_question
  has_many :user_quiz_answers
end

app/models/quiz_question.rb
class QuizQuestion < ApplicationRecord
  belongs_to :quiz
  has_many :quiz_answers
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/school.rb
class School < ApplicationRecord
  has_many :courses
  has_one_attached :logo
  before_save :capitalize_name
  def capitalize_name
    self.name=self.name.split.map(&:capitalize).join(' ')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # authenticates_with_sorcery!
  attr_accessor :skip_password, :uid, :redirect_page
  validates :cpf, length: { is: 14 }, uniqueness: true
  has_many :certificates
  has_many :contact_us_conversations
  has_many :course_registrations
  has_one_attached :avatar
end

app/controllers/course_ratings_controller.rb
class CourseRatingsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    courses_ratings = CourseRating.all
    hash_ratings = courses_ratings.map do |c|
      {'course_id' => c.course_id,
       'rating' => c.rating,
       'obsevation' => c.observation,
      }
    end
    render status: 200, json: {
        avalicoes: hash_ratings,
    }.to_json
  end

  def avaliar_curso
    if CourseRating.where(course_id: params[:course_rating][:course_id], user_id: params[:course_rating][:user_id]).count == 0
      if (params[:course_rating][:rating]).to_f > 5.0 or (params[:course_rating][:rating]).to_f < 0.0
        render status: 400, json: {
            message: "A nota está fora do intervalo! Coloque uma nota entre 0 e 5.",
        }.to_json
      else
        @course_rating = CourseRating.new(course_rating_params)
        if @course_rating.save
          render status: 200, json: {
              message: "Avaliação feita com sucesso",
          }.to_json
        else
          render status: 400, json: {
              message: "Não foi possível avaliar esse curso",
          }.to_json
        end
      end
    else
      render status: 400, json: {
          message: "A avaliação para este curso já foi feita",
      }.to_json
    end
  end

    def course_rating_params
      params.require(:course_rating).permit(:course_id, :user_id, :rating, :observation)
    end
end

app/helpers/course_ratings_helper.rb
module CourseRatingsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/course_ratings/_form.html.erb
<%= form_with(model: course_rating, local: true) do |form| %>
  <% if course_rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course_rating.errors.count, "error") %> prohibited this course_rating from being saved:</h2>

      <ul>
      <% course_rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.text_field :course_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="field">
    <%= form.label :observation %>
    <%= form.text_area :observation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/course_ratings/edit.html.erb
<h1>Editing Course Rating</h1>

<%= render 'form', course_rating: @course_rating %>

<%= link_to 'Show', @course_rating %> |
<%= link_to 'Back', course_ratings_path %>

app/views/course_ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Course Ratings</h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>User</th>
      <th>Rating</th>
      <th>Observation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @course_ratings.each do |course_rating| %>
      <tr>
        <td><%= course_rating.course %></td>
        <td><%= course_rating.user %></td>
        <td><%= course_rating.rating %></td>
        <td><%= course_rating.observation %></td>
        <td><%= link_to 'Show', course_rating %></td>
        <td><%= link_to 'Edit', edit_course_rating_path(course_rating) %></td>
        <td><%= link_to 'Destroy', course_rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course Rating', new_course_rating_path %>

app/views/course_ratings/new.html.erb
<h1>New Course Rating</h1>

<%= render 'form', course_rating: @course_rating %>

<%= link_to 'Back', course_ratings_path %>

app/views/course_ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @course_rating.course %>
</p>

<p>
  <strong>User:</strong>
  <%= @course_rating.user %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @course_rating.rating %>
</p>

<p>
  <strong>Observation:</strong>
  <%= @course_rating.observation %>
</p>

<%= link_to 'Edit', edit_course_rating_path(@course_rating) %> |
<%= link_to 'Back', course_ratings_path %>